### ISSUE TITLE
Unexpected string

### ISSUE THREAD

**Issue by Diokuz** [AgentME/flow-copy-source#11]
Some of my react components are _redirected_ for backward compatibility. But it breaks flow:

`src/fields/InputSelect/InputSelect.js`:
```js
export default from '../../organisms/InputSelect/InputSelect'
```
Error:
```
node_modules/.bin/flow
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/***/lib/fields/InputSelect/InputSelect.js.flow:1:21

Unexpected string

     1│ export default from '../../organisms/InputSelect/InputSelect'
     2│


```

Is it a `flow` bug, or `flow-copy-source`?

**Comment by AgentME** [comment]
That error doesn't ring any bells to me. Without more information, I'd have to assume it's a flow issue or an issue with how you've configured flow. Flow-copy-source does one job without much variation so I'd be surprised if it could be at fault here.

**Comment by Diokuz** [comment]
Looks like you cant just rename file to `file.flow` and expect it to be valid `flow` definition.
But I expected that after I read your readme )

**Comment by TrySound** [comment]
@Diokuz Do you have `// @flow` in that file?
