### ISSUE TITLE
--ignore flag doesn't seem to exclude files

### ISSUE THREAD

**Issue by thomb** [AgentME/flow-copy-source#2]
I'm running the following command
`flow-copy-src ./src ./build -i **/index.js`

And receive the following error

```
[ { Error: ENOTDIR: not a directory, unlink '/local/path/src/index.js/index.js.flow'
      at Error (native)
    errno: -20,
    code: 'ENOTDIR',
    syscall: 'unlink',
    path: '/local/path/src/index.js/index.js.flow' } ]
```

But if I run this `glob` manually - looking at the way `src/kefir-glob` is invoked from 'flowCopySource` - like so:
`new Glob('**/*.js?(x)', {cwd: './src', strict: true, ignore: '**/index.js`})`

I get the correct list of file I want to be copied.

I haven't gone further into the behaviour of `flowCopySource`, but this seems incorrect behaviour.

I've created my own script to do mimic the behaviour of this lib, using `fs-extra` to copy the files, without implementing `kefir` which works without issue.

Am I missing something? Holding it wrong? 

Thanks in advance!

**Comment by AgentME** [comment]
When you run `flow-copy-src ./src ./build -i **/index.js` in bash, the `**/index.js` part will get expanded into one or more filenames by bash before the arguments are passed to flow-copy-source. If you want to pass a glob expression as-is to a program, then you need to quote it: `flow-copy-src ./src ./build -i '**/index.js'`. Let me know if this fixes your issue.

**Comment by thomb** [comment]
Well look at me herping all the derps! 
That indeed solves my problem. Thanks for the heads up, much appreciated.
